name: Compile ZMK
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/boards/shields/*.conf"
      - "config/boards/shields/*.overlay"
      - "config/boards/*/*/*.keymap"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
